"""
Demo pipeline. No network, no API key. Returns a realistic, task-shaped
response so the UI can be exercised end-to-end.

The demo is now task-aware: it inspects the task text and produces a
plausible deliverable for code, writing, analysis, or generic tasks instead
of always returning the same canned Python snippet.
"""
from __future__ import annotations

import re
import time
from dataclasses import dataclass

from .pipeline import AgentStep, PipelineResult, to_wire


_CODE_HINTS = (
    "function", "code", "implement", "script", "algorithm", "class ",
    "python", "javascript", "typescript", "rust", "go ", "java ", "c++",
    "compile", "debug", "refactor", "module", "library", "api ", "endpoint",
    "sql", "regex", "parse", "html", "css", "react",
)
_WRITING_HINTS = (
    "write", "blog", "essay", "story", "article", "letter", "email",
    "caption", "headline", "tagline", "speech", "press release",
)
_ANALYSIS_HINTS = (
    "analyze", "analyse", "compare", "evaluate", "assess", "review",
    "explain", "summarise", "summarize", "research", "report",
    "strategy", "plan", "swot",
)


def classify_task(task: str) -> str:
    t = task.lower()
    if any(h in t for h in _CODE_HINTS):
        return "code"
    if any(h in t for h in _WRITING_HINTS):
        return "writing"
    if any(h in t for h in _ANALYSIS_HINTS):
        return "analysis"
    return "generic"


def _extract_topic(task: str) -> str:
    """Best-effort topic extraction so the demo feels relevant, not random."""
    # Pull the part after the first verb-ish word if present.
    text = task.strip()
    # Drop a leading "write a ...", "implement a ...", "build a ..."
    m = re.match(
        r"^(?:please\s+)?(?:write|build|implement|create|design|make|generate|develop|craft|draft|analyze|analyse|explain|compare)\s+(?:a|an|the)?\s*(.+)$",
        text,
        re.IGNORECASE,
    )
    if m:
        return m.group(1).strip().rstrip(".!?")
    return text.rstrip(".!?")


def _demo_code_solution(topic: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", topic.lower()).strip("_") or "task"
    return (
        f"# Solution: {topic}\n"
        f"# Generated by the Omni-Loop Swarm demo (no live model was called).\n"
        f"# Switch off DEMO mode and add an API key in Settings to run the\n"
        f"# full Builder -> Reviewer -> Remediation -> Master pipeline against a real model.\n\n"
        f"def solve_{slug}(input_data):\n"
        f'    """Implement the requested behaviour for: {topic}."""\n'
        f"    if not input_data:\n"
        f"        raise ValueError(\"input_data is required\")\n"
        f"    # ...real implementation goes here when running in LIVE mode...\n"
        f"    return input_data\n"
    )


def _demo_writing_solution(topic: str) -> str:
    return (
        f"# {topic.title()}\n\n"
        f"This is a demo draft produced by the Omni-Loop Swarm Engine without "
        f"calling a live model. In LIVE mode, the BUILDER agent produces a full "
        f"first draft on this exact topic, the REVIEWER scores it against your "
        f"task and constraints, REMEDIATION rewrites the parts the reviewer "
        f"flagged, and the MASTER REVIEWER grants final approval before it is "
        f"shown to you here.\n\n"
        f"## Why the loop matters\n\n"
        f"Most single-shot generations ship with at least one issue a strict "
        f"reviewer would catch — missing edge case, wrong tone, untested claim. "
        f"The closed loop catches those before they reach you.\n\n"
        f"## How to try it for real\n\n"
        f"1. Toggle off DEMO mode in the header.\n"
        f"2. Open Settings and add your API key + model + base URL.\n"
        f"3. Replace the demo task with your real one and run the swarm.\n"
    )


def _demo_analysis_solution(topic: str) -> str:
    return (
        f"# Analysis: {topic}\n\n"
        f"## Summary\n"
        f"Demo analysis produced without calling a live model. In LIVE mode the "
        f"BUILDER writes the full first-pass analysis, the REVIEWER critiques it "
        f"for gaps, REMEDIATION fixes those gaps, and the MASTER REVIEWER signs off.\n\n"
        f"## Key dimensions to cover\n"
        f"- Scope and boundaries of {topic}\n"
        f"- Stakeholders and tradeoffs\n"
        f"- Risks and mitigations\n"
        f"- Recommendations and next steps\n\n"
        f"## Recommendation\n"
        f"Run a single LIVE execution against your preferred model to replace "
        f"this stub with a real analysis.\n"
    )


def _demo_generic_solution(topic: str) -> str:
    return (
        f"# Output for: {topic}\n\n"
        f"This is a demo response from the Omni-Loop Swarm Engine. No live model "
        f"was called. In LIVE mode the full closed-loop pipeline runs against "
        f"your configured provider and the result replaces this stub.\n\n"
        f"Tip: open Settings, paste your API key, pick a model, and switch off "
        f"DEMO mode to see the real pipeline.\n"
    )


def run_demo_pipeline(task: str, *, loop_count: int = 0) -> PipelineResult:
    """Simulate the pipeline. `loop_count` is fixed so tests are deterministic;
    the route can override it for visual variety."""
    started = time.monotonic()
    time.sleep(0.2)  # tiny delay so the UI animation doesn't flash

    topic = _extract_topic(task)
    kind = classify_task(task)
    if kind == "code":
        solution = _demo_code_solution(topic)
    elif kind == "writing":
        solution = _demo_writing_solution(topic)
    elif kind == "analysis":
        solution = _demo_analysis_solution(topic)
    else:
        solution = _demo_generic_solution(topic)

    builder_evidence = (
        f"Produced an initial {kind} deliverable for \"{topic[:80]}\". "
        f"Approach covers the core requirement directly and keeps the implementation self-contained."
    )

    first_decision = "FAIL" if loop_count else "PASS"
    first_evidence = (
        "Missing an edge case for empty input and no error handling around the main path."
        if loop_count
        else "Solution directly satisfies the stated task with no missing requirements found."
    )

    steps: list[AgentStep] = [
        AgentStep(
            name="BUILDER",
            role="builder",
            evidence=builder_evidence,
            payload={"solution": solution},
            elapsed_seconds=0.05,
        ),
        AgentStep(
            name="REVIEWER",
            role="reviewer",
            evidence=first_evidence,
            payload={"decision": first_decision},
            elapsed_seconds=0.04,
        ),
    ]

    if loop_count:
        steps.append(AgentStep(
            name=f"REMEDIATION (loop {loop_count})",
            role="remediation",
            evidence=(
                "Added input validation and a guard clause for the empty-input case; "
                "wrapped the main path in error handling as required by the reviewer."
            ),
            payload={"solution": solution, "loop": loop_count},
            elapsed_seconds=0.06,
        ))
        steps.append(AgentStep(
            name=f"RE-REVIEW (loop {loop_count})",
            role="reviewer",
            evidence="Previously identified issues are resolved. Solution now handles edge cases correctly.",
            payload={"decision": "PASS", "loop": loop_count},
            elapsed_seconds=0.04,
        ))

    steps.append(AgentStep(
        name="MASTER REVIEWER",
        role="master_reviewer",
        evidence=(
            "Solution is complete, addresses the task and constraints, and shows no remaining "
            "production risk. Approved for release."
        ),
        payload={"approval": "GRANTED"},
        elapsed_seconds=0.05,
    ))

    return PipelineResult(
        steps=steps,
        final_output=solution,
        approval="GRANTED",
        loop_count=loop_count,
        tokens={"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0},
        model="demo",
        total_elapsed_seconds=time.monotonic() - started,
    )
